config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact", as: "teams"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @employees = ["sam", "Luis", "Loulou"]

  end

  def about
  end

  def contact
    @employees = ["Sam", "Luis", "Loulou"]
    query = params[:member].capitalize
    if query.present?
      @employees = @employees.select { |employee| query == employee }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LectureApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- nav -->
    <div class="main-desktop-nav" style="height: 50px; background: gray; width: 100%"></div>
    <%= yield %>
    <div class="footer" style="height: 50px; background: gray; width: 100%"></div>
    <!-- footer -->
  </body>
</html>

app/views/pages/about.html.erb
<p>Hello world!</p>

app/views/pages/contact.html.erb
<h1>Contact us!</h1>
<input type="text"
       name="member"
       value="<%= params[:member] %>"
       placeholder="Who are you looking for?">
<ul>
  <% @employees.each do |employee| %>
    <li><%= employee.capitalize %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>Welcome to our app!</h1>
<!-- <a href="/contact">Contact</a> -->
<%= link_to "Contact" , teams_path %>
<ul>
  <% @employees.each do |employee| %>
    <li><%= employee.capitalize %></li>
  <% end %>
</ul>

<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?">
  <input type="submit">
</form>